name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Setup Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
      
    - name: Install Dependancies
      run: |
        python -m pip install requirements.txt
        pip install -r requirements.txt

    - name: Run flake8 on front-end
      run: |
        flake8 app/app.py --max-line-length=127 --exit-zero --statistics
